name: mci_sentry
services:
    redis:
        container_name: sentry-redis
        image: redis
    postgres:
        container_name: sentry-postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: sentry
    sentry:
        container_name: my-sentry
        image: sentry
        ports:
            - "8080:9000"
        environment:
            SENTRY_SECRET_KEY: '(t(e22qa+hx4%hllqrno)4sr=6ki^t@#zfpk_cvsfg=0i0cpvr'
        depends_on:
            - redis
            - postgres
    sentry-cron:
        container_name: sentry-cron
        image: sentry
        environment:
            SENTRY_SECRET_KEY: '(t(e22qa+hx4%hllqrno)4sr=6ki^t@#zfpk_cvsfg=0i0cpvr'
        depends_on:
            - redis
            - postgres
        command: "run cron"
    sentry-worker-1:
        container_name: sentry-worker-1
        image: sentry
        environment:
            SENTRY_SECRET_KEY: '(t(e22qa+hx4%hllqrno)4sr=6ki^t@#zfpk_cvsfg=0i0cpvr'
        depends_on:
            - redis
            - postgres
        command: "run worker"